import { SeederInterface } from './interfaces/seeder.interface';
import { PrismaClient } from '@prisma/client';

export default class FaqSeeder implements SeederInterface {
  async run(prisma: PrismaClient) {
    await prisma.faq.deleteMany();

    for (const item of this.getItems()) {
      await prisma.faq.create({
        data: {
          ...item,
        },
      });
    }
  }

  private getItems() {
    return [
      {
        question: 'What is EstateHack?\n',
        answer:
          'EstateHack is a Google Chrome extension designed to simplify section 8 property evaluations for real estate investors, agents, assistants and wholesalers.',
        sort_order: 0,
      },
      {
        question: 'Where is the rental data coming from?',
        answer:
          'Our rental data is sourced from reputable public databases such as the U.S. Department of Housing and Urban Development website (<a href="http://hud.gov/">HUD.gov</a>)',
        sort_order: 1,
      },
      {
        question: 'How often is the data updated?\n',
        answer:
          'Our data is updated regularly to ensure you have access to the latest information from government websites.',
        sort_order: 2,
      },
      {
        question:
          'Can I export the evaluation reports generated by EstateHack?\n',
        answer:
          'Yes, you can export detailed evaluation reports in various formats, including PDF and CSV, for easy sharing and analysis.',
        sort_order: 3,
      },
      {
        question:
          'Is EstateHack suitable for evaluating multifamily properties?\n',
        answer:
          'While EstateHack is primarily designed for single family properties, it also includes features that can be useful for evaluating multifamily listings.',
        sort_order: 4,
      },
      {
        question: 'What happens if I encounter an issue with the software?\n',
        answer:
          'If you encounter any issues, our support team is available 24/7 to assist you, and we provide a comprehensive help center with troubleshooting guides and tutorials.',
        sort_order: 5,
      },
      {
        question: 'How do I install the Chrome Extension?\n',
        answer:
          'You can install the EstateHack Chrome Extension from the Chrome Web Store by searching for "EstateHack" and clicking "Add to Chrome."',
        sort_order: 6,
      },
      {
        question: 'Can I use EstateHack on multiple devices?\n',
        answer:
          'Yes, your EstateHack account can be accessed on multiple devices, including desktops, laptops, and tablets.',
        sort_order: 7,
      },
      {
        question: 'How can I cancel the subscription?\n',
        answer:
          'You can easily cancel your subscription through the account settings or contact our support team for assistance.',
        sort_order: 8,
      },
    ];
  }
}
